### ISSUE TITLE
About unit bearing vector

### ISSUE THREAD

**Issue by lnexenl** [javrtg/C2P#1]
Hi, I am curious about what does unit bearing vector mean. If I have a undistorted point [x, y], what should I do to convert it to an unit bearing vector? Should I just normalize [x, y, 1] or transform point to normalized plane and then convert it to bearing vector?

**Comment by javrtg** [comment]
Hi! In this work we follow the notation used (and I believe proposed) in Prof. L. Kneip's works, as documented in [`OpenGV`](https://laurentkneip.github.io/opengv/page_how_to_use.html#:~:text=Vocabulary-,Bearing%20vector,-%3A%20A%20bearing%20vector) and adopted in works like [[Kneip, 2013](https://openaccess.thecvf.com/content_iccv_2013/papers/Kneip_Direct_Optimization_of_2013_ICCV_paper.pdf)], [[Lee, 2021](https://openaccess.thecvf.com/content/CVPR2021/papers/Lee_Rotation-Only_Bundle_Adjustment_CVPR_2021_paper.pdf)] and [[Zhao, 2022](https://ieeexplore.ieee.org/abstract/document/9220804)].

This means that a bearing vector $\mathbf{f}$ can be obtained using the "*unprojection function*", which depends on the camera model used (e.g., pinhole, Kannala-Brandt, etc.) and requires the intrinsic parameters to be known.

Formally, this unprojection function maps a (possibly distorted) point $\mathbf{p}$ in the image plane to the unit sphere:
$$\pi^{-1}: \quad \mathbb{R}^2 \to \mathcal{S}^2 \quad ; \quad  \mathbf{p} \mapsto \mathbf{f} = \pi^{-1}(\mathbf{p})$$ 

Indeed, what you mentioned is exactly the process for pinhole cameras : 1) Unprojection to the normalized image plane and 2) norm normalization to be unitary. In code, this could be achieved, e.g., by:
```python
import numpy as np

# (3, 3) array with pinhole calibration matrix:
K = ...
# (2, n) array of image points in pixel units:
p = ...
# a) points in homogeneous coordinates:
ph = np.vstack((p, np.ones(p.shape[1])))
# b) express points in normalized image plane:
pn = np.linalg.inv(K) @ ph
# c) normalize points to unit length to obtain the bearing vectors:
f = pn / np.linalg.norm(pn, axis=0, keepdims=True)
```
Steps `a)`, `b` and `c)` in comments are encompassed by the unprojection function $\pi^{-1}$ mentioned above. 

However, note that this function can vary significantly depending on the camera model used. Sometimes, unlike with the pinhole model, there is no closed-form function for this unprojection, and the roots of a polynomial need to be numerically computed, as in the [Kannala-Brandt model](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=1642666) or its slightly different [OpenCV implementation](https://docs.opencv.org/4.x/db/d58/group__calib3d__fisheye.html). 

On the other hand, other models, more general than the pinhole and specially suitable for high FoV cameras, directly provide a closed-form unprojection function, like the [EUCM camera model](https://hal.science/hal-01722264/file/calibration.pdf). A great review of multiple popular camera models can be found in [[Usenko, 2018](https://arxiv.org/abs/1807.08957)].

I hope this helps! Let me know if you have any further questions.

**Comment by lnexenl** [comment]
Thank you so much! I will try later
